import SwiftUI

enum TextName {
    static let submission: String = "제출하기"
    static let completeSubmit: String = "제출 완료"
    static let checkMyPage: String = "마이페이지에서 확인할 수 있어요!"
    static let answerText: String = "질문에 대한 나의 생각을 적어보세요."
    static let privateAnswer: String = "내 생각 나만 볼래요"
    static let selectAct: String = "행동 선택"
    static let editText: String = "수정하기"
    static let deleteText: String = "삭제하기"
    static let reportText: String = "신고하기"
    static let checkDelete: String = "정말 삭제하실 건가요?"
    static let deleteIt: String = "삭제할래요"
    static let noText: String = "아니요"
    static let checkDeleteText: String = "삭제하신 답변은 복구할 수 없어요 ㅠ^ㅠ\n신중하게 생각하고 선택해주세요."
    static let selectReport: String = "게시글 신고 사유를 선택해주세요"
    static let completeText: String = "작성완료:)"
    static let deleteBoard: String = "게시글을 삭제하시겠습니까?"
    static let showMyThink: String = "내 생각 보기"
    static let myAnswerText: String = "내가 답한 질문"
    static let myQuestionText: String = "내가 만든 질문"
    static let writeThink: String = "생각적기"
    static let closeText: String = "닫기"
    static let characterName: String = "곰민"
    static let favoriteCategoryText: String = "관심 카테고리"
    static let guideQuesition: String = "평소 궁금했거나\n좋은 질문이 있으신가요?"
    static let freeAnythingText: String = "무엇이든지 자유롭게 적어주세요!"
    static let checkShareMyThink: String = "내 생각 공유하기"
    static let openMyThink: String = "내가 작성한 질문이 모두에게 공개되요"
    static let makeQuestion: String = "질문 만들기"
    static let okText: String = "완료"
    static let oneStepYourself: String = "스스로에게 한발짝 더 다가갔군요?"
    static let uploadBoardText: String = "게시판에 내가 쓴 질문이 올라갔어요!"
    static let stackMyQuestion: String = "보관함에 내가 쓴 질문이 한개 더 쌓였네요!"
    static let goLocker: String = "보관함으로 가볼래요?"
    static let choosingDone: String = "다 골랐어요!"
}
